### PR TITLE
Rebuild sparsity pattern after rebuilding constraints

### LINKED ISSUE #612: Manifold geometries with a free surface crach
I am testing the ellipsoidal geometry model, and for this I am testing how it works together with different parts of ASPECT, and especially the free surface. During the testing I stumbled upon a curious bug which seems to be in the constraints part of the free surface code. I have been able to get some constrains on the bug, in the sense that it occurs in combination with at least the spherical shell, chunk and ellipsoidal chunk geometries when using tangential velocity boundary conditions (all the geometries which use manifolds).

The simplest way to reproduce this error is by taking the shell_simple_3d.prm cookbook file and add

  set Pressure normalization             = no
  set CFL number = 0.1

and set in the model section:

  set Zero velocity boundary indicators       =
  set Tangential velocity boundary indicators = inner,east,south,west
  set Prescribed velocity boundary indicators =
  set Free surface boundary indicators        = outer

I also had to remove depth average from the list of postprocessors, because it gave some strange error.

The bug shows itself at the beginning of timestep 2:
```
*** Timestep 2:  t=20425.1 years
------------------------------------------
Got error 2 in row 7537 of proc 15 when trying to add the columns:
481 482 483 484 3052 3053 3054 3055 5194 5195 5196 5197 7537 7538 7539 7540

Matrix row  has the following indices:
7537 7538 7539 7540 7546 7547 7551 7552 7570 7571 7575 7576 7587 7588 7597 7598 7599 7600 7606 7607 7611 7612 7630 7631 7635 7636 7647 7648 482 484 483 480 3053 3051 3055 3054 3101 3103 3102 3099 5233 5194 5196 5245 5197 5244 5232 5228 5195 5227
```
and in the error output the following:
```
--------------------------------------------------------
An error occurred in line <1659> of file </home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/source/lac/trilinos_sparse_matrix.cc> in function
    void dealii::TrilinosWrappers::SparseMatrix::add(dealii::TrilinosWrappers::SparseMatrix::size_type, dealii::TrilinosWrappers::SparseMatrix::size_type, const size_type*, const double*, bool, bool)
The violated condition was:
    ierr <= 0
The name and call sequence of the exception was:
    ExcAccessToNonPresentElement(row, col_index_ptr[0])
Additional Information:
You tried to access element (10005/3087) of a sparse matrix, but it appears to not exist in the Trilinos sparsity pattern.

Stacktrace:
-----------
#0  /home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/build/lib/libdeal_II.g.so.8.3.pre: dealii::TrilinosWrappers::SparseMatrix::add(unsigned int, unsigned int, unsigned int const*, double const*, bool, bool)
#1  /home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/build/lib/libdeal_II.g.so.8.3.pre: void dealii::ConstraintMatrix::distribute_local_to_global<dealii::TrilinosWrappers::SparseMatrix, dealii::TrilinosWrappers::MPI::Vector>(dealii::FullMatrix<double> const&, dealii::Vector<double> const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, dealii::TrilinosWrappers::SparseMatrix&, dealii::TrilinosWrappers::MPI::Vector&, bool, dealii::internal::bool2type<false>) const
#2  ./aspect: aspect::Simulator<3>::FreeSurfaceHandler::solve_elliptic_problem()
#3  ./aspect: aspect::Simulator<3>::FreeSurfaceHandler::execute()
#4  ./aspect: aspect::Simulator<3>::solve_timestep()
#5  ./aspect: aspect::Simulator<3>::run()
#6  ./aspect: main
--------------------------------------------------------

[node017:08191] *** Process received signal ***
[node017:08191] Signal: Aborted (6)
[node017:08191] Signal code:  (-6)
[node017:08191] [ 0] /lib64/libpthread.so.0[0x3dc6c0f490]
[node017:08191] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x3dc6832945]
[node017:08191] [ 2] /lib64/libc.so.6(abort+0x175)[0x3dc6834125]
[node017:08191] [ 3] /home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/build/lib/libdeal_II.g.so.8.3.pre(_ZN6dealii18deal_II_exceptions9internals5abortERKNS_13ExceptionBaseEb+0x3b)[0x7ffff5dc5f38]
[node017:08191] [ 4] /home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/build/lib/libdeal_II.g.so.8.3.pre(_ZN6dealii18deal_II_exceptions9internals11issue_errorINS_16TrilinosWrappers12SparseMatrix28ExcAccessToNonPresentElementEEEvNS1_17ExceptionHandlingEPKciS8_S8_S8_T_+0x34)[0x7ffff5c770e6]
[node017:08191] [ 5] /home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/build/lib/libdeal_II.g.so.8.3.pre(_ZN6dealii16TrilinosWrappers12SparseMatrix3addEjjPKjPKdbb+0xac7)[0x7ffff5c73231]
[node017:08191] [ 6] /home/aspect/deal.ii/deal.ii_2015-06-04-v11.4/dealii/build/lib/libdeal_II.g.so.8.3.pre(_ZNK6dealii16ConstraintMatrix26distribute_local_to_globalINS_16TrilinosWrappers12SparseMatrixENS2_3MPI6VectorEEEvRKNS_10FullMatrixIdEERKNS_6VectorIdEERKSt6vectorIjSaIjEERT_RT0_bNS_8internal9bool2typeILb0EEE+0x5bf)[0x7ffff5783da3]
[node017:08191] [ 7] ./aspect(_ZN6aspect9SimulatorILi3EE18FreeSurfaceHandler22solve_elliptic_problemEv+0x6de)[0x906d08]
[node017:08191] [ 8] ./aspect(_ZN6aspect9SimulatorILi3EE18FreeSurfaceHandler7executeEv+0x61)[0x9083ab]
[node017:08191] [ 9] ./aspect(_ZN6aspect9SimulatorILi3EE14solve_timestepEv+0x11a)[0x8eb0f2]
[node017:08191] [10] ./aspect(_ZN6aspect9SimulatorILi3EE3runEv+0x44f)[0x8f3d9b]
[node017:08191] [11] ./aspect(main+0x4c5)[0x99a751]
[node017:08191] [12] /lib64/libc.so.6(__libc_start_main+0xfd)[0x3dc681ec9d]
[node017:08191] [13] ./aspect[0x625c89]
```
I am not exactly causes the problem. Could it for example be caused by the decoupling of the manifold by the free surface code? If needed I can also attach input files where the problem occurs for both the chunk and ellipsoidal chunk geometry.

Many thanks!

Menno

### PR DESCRIPTION
**Pull request by ian-r-rose**
This is an attempt to fix #612.

This was a difficult bug to reproduce and track down, so I'd appreciate it if @MFraters could check if this fixes the problem he was seeing. The basic problem was that we are rebuilding the constraints on the mesh motion at every time-step, but only setting up the sparsity pattern for the remeshing matrix after redistributing the mesh. In certain difficult-to-predict cases (especially when tangential constraints are involved) the sparsity pattern can be no longer valid for the computed constraints.

The fix here is just to rebuild the sparsity pattern after rebuilding the constraints object. This should be somewhat less efficient, but I don't think that this step was very expensive to begin with.

Thoughts?

### CODE REVIEW

**Comment by bangerth** [comment]
I think in reality you only need to rebuild the sparsity pattern if you either change the mesh or change the constraints. 

That said, I think the overhead of rebuilding the sparsity pattern is relatively small.

**Comment by ian-r-rose** [comment]
My confusion was (and still is) that I did not think that the overall structure/coupling of the constraints were changing from step to step, just the specific values. I would then think that the sparsity pattern would not need to be rebuilt.

I guess that is not true in all cases (?).

**Comment by bangerth** [comment]
@ian-r-rose : Imagine you have a tangential flow constraint `n.u=0` at the top. If your original geometry is a box, then this constraint has the form `nx*ux+ny*uy=0` and because `nx=0` this means that the weight zero is dropped and you simply get the constraint `uy=0`. Whenever you write into the line for `uy`, no additional writes happen into the line for `ux` -- or, more specifically, only zero additions to the matrix --, and consequently we don't allocate these nonzero entries.

Now consider that you change your geometry because you evolve the upper surface somehow. You then get a constraint of the form `uy=nx/ny*ux` with a nonzero weight on the right hand side. So, if you write into the line for `uy`, it will result in other writes to line `ux` because of this constraint. In other words, you now get nonzero additions to the matrix for which you actually need the entry in the sparsity pattern that then makes sure we also create the entry in the matrix.

So, changing constraints may in fact change what sparsity pattern you need, even if the *structure* of the constraints remains exactly the same.

**Comment by ian-r-rose** [comment]
Ah, that makes perfect sense, thanks Wolfgang.  

In that case, I believe that this patch should fix the issue, though it may be best to wait until @MFraters confirms.

**Comment by MFraters** [comment]
Hey Ian and wolfgang,

Thanks for looking so quickly into this. Unfortunately I won't have access to a computer with a terminal till sunday evening.





On Fri, Sep 25, 2015 at 3:05 PM -0700, "Ian Rose" <notifications@github.com> wrote:
Ah, that makes perfect sense, thanks Wolfgang.

In that case, I believe that this patch should fix the issue, though it may be best to wait until @MFraters confirms.

---

**Comment by MFraters** [comment]
I can confirm it fixes the problem for the test cases. Thanks for the fix!

**Comment by tjhei** [comment]
@ian-r-rose This patch will now couple all components in the sparsity pattern. Is that on purpose/needed?

**Comment by ian-r-rose** [comment]
@tjhei Yes, the coupling is due to the tangential boundary constraints  (though I suppose I could do a check for when there are those constraints, and only do the coupling in those cases).

**Comment by bangerth** [comment]
I don't think you need this. The coupling only happens on the boundary. You should be able to get away with using the "diagonal" `coupling` argument and let the constraints deal with the coupling between components on the boundary.

**Comment by tjhei** [comment]
correct, tangential constraints will add individual entries that couple the components, but that is not what the coupling structure in ```make_sparsity_pattern``` is about. That is about "do the components couple in your assembly" (and they don't).

**Comment by ian-r-rose** [comment]
Okay, my misunderstanding.  I have decoupled the DoFs.

File: source/simulator/freesurface.cc [hunk 1]
```diff
@@ -377,7 +379,39 @@ namespace aspect
     Vector<double> cell_vector (dofs_per_cell);
     FullMatrix<double> cell_matrix (dofs_per_cell, dofs_per_cell);
 
-    mesh_matrix = 0;
+    mesh_matrix.clear ();
+
+    //The degrees of freedom for different dimensions do not couple,
+    //so we are just solving a Laplacian for each spatial direction
```
Comment (tjhei) [inline source/simulator/freesurface.cc]: I think the reasoning is the other way around: "We are just solving a Laplacian for each spatial direction, so the DoFs of different components do not couple".

**Comment by tjhei** [comment]
Can you add a changelog entry?

**Comment by tjhei** [comment]
(looks good to me)

**Comment by ian-r-rose** [comment]
This should be good to go now.
