### PR TITLE
Fix spherical shell restart. Add test.

### LINKED ISSUE #4021: Errors with restart from checkpoint for current deal.ii development version
I'm trying to write and resume from a checkpoint with the current development versions of deal.ii and aspect. I have verified that I can do this successfully using deal.ii-9.2 and aspect from February, but that this functionality is broken. The model setup in question has prescribed surface velocity boundary conditions.

I suspect that the error is associated with a recent change in deal.ii. I do not understand the classes being used in `core.cc:1872-1909`. Maybe it is necessary to call `map->initialize` when resuming from snapshot?

```-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.3.0-pre (master, 5d2ce34ea)
--     . using deal.II 9.3.0-pre (master, dd40ea034d)
--     .       with 32 bit indices and vectorization level 1 (128 bits)
--     . using Trilinos 12.10.1
--     . using p4est 2.0.0
--     . running in DEBUG mode
--     . running with 192 MPI processes
-----------------------------------------------------------------------------


   Setting up GPlates boundary velocity plugin.


   Loading GPlates data boundary file ZZ+S200/velo_ZZ+S200_458.gpml.


   Loading new gplates velocity file did not succeed.
   Assuming constant boundary conditions for rest of model run.

-----------------------------------------------------------------------------
-- For information on how to cite ASPECT, see:
--   https://aspect.geodynamics.org/citing.html?ver=2.3.0-pre&dg=1&sha=5d2ce34ea&src=code
-----------------------------------------------------------------------------
*** Resuming from snapshot!

Number of active cells: 49,152 (on 4 levels)
Number of degrees of freedom: 3,001,642 (1,216,710+52,258+405,570+1,327,104)


--------------------------------------------------------
An error occurred in line <721> of file </tmp/unpack/deal.II-master/source/fe/mapping_q_cache.cc> in function
    std::vector<dealii::Point<spacedim> > dealii::MappingQCache<<anonymous>, <anonymous> >::compute_mapping_support_points(const typename dealii::Triangulation<dim, spacedim>::cell_iterator&) const [with int dim = 3; int spacedim = 3; typename dealii::Triangulation<dim, spacedim>::cell_iterator = dealii::TriaIterator<dealii::CellAccessor<3, 3> >]
--------------------------------------------------------
--------------------------------------------------------
An error occurred in line <721> of file </tmp/unpack/deal.II-master/source/fe/mapping_q_cache.cc> in fu
nction
    std::vector<dealii::Point<spacedim> > dealii::MappingQCache<<anonymous>, <anonymous> >::compute_map
ping_support_points(const typename dealii::Triangulation<dim, spacedim>::cell_iterator&) const [with in
t dim = 3; int spacedim = 3; typename dealii::Triangulation<dim, spacedim>::cell_iterator = dealii::Tri
aIterator<dealii::CellAccessor<3, 3> >]
The violated condition was:
    support_point_cache.get() != nullptr
Additional information:
    Must call MappingQCache::initialize() before using it or after mesh
    has changed!

Stacktrace:
-----------
#0  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: dealii::MappingQCache<3, 3>::compute_mapping_support_points(dealii::TriaIterator<dealii::CellAccessor<3, 3> > const&) const
#1  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: dealii::MappingQGeneric<3, 3>::fill_fe_face_values(dealii::TriaIterator<dealii::CellAccessor<3, 3> > const&, unsigned int, dealii::hp::QCollection<2> const&, dealii::Mapping<3, 3>::InternalDataBase const&, dealii::internal::FEValuesImplementation::MappingRelatedData<3, 3>&) const
#2  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: dealii::FEFaceValues<3, 3>::do_reinit(unsigned int)
#3  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: void dealii::FEFaceValues<3, 3>::reinit<false>(dealii::TriaIterator<dealii::DoFCellAccessor<3, 3, false> > const&, unsigned int)
#4  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: void dealii::hp::FEFaceValues<3, 3>::reinit<false>(dealii::TriaIterator<dealii::DoFCellAccessor<3, 3, false> > const&, unsigned int, unsigned int, unsigned int, unsigned int)
#5  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: void dealii::VectorTools::compute_nonzero_normal_flux_constraints<3, 3>(dealii::DoFHandler<3, 3> const&, unsigned int, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, std::map<unsigned int, dealii::Function<3, double> const*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, dealii::Function<3, double> const*> > > const&, dealii::AffineConstraints<double>&, dealii::Mapping<3, 3> const&)
#6  /home/rudolph/sw/dealii-toolchain-openmpi-4.0.5-mpiio-04252021/deal.II-master/lib/libdeal_II.g.so.9.3.0-pre: void dealii::VectorTools::compute_no_normal_flux_constraints<3, 3>(dealii::DoFHandler<3, 3> const&, unsigned int, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&, dealii::AffineConstraints<double>&, dealii::Mapping<3, 3> const&)
#7  ./aspect-mpiio: aspect::Simulator<3>::compute_initial_velocity_boundary_constraints(dealii::AffineConstraints<double>&)
#8  ./aspect-mpiio: aspect::Simulator<3>::setup_dofs()
#9  ./aspect-mpiio: aspect::Simulator<3>::resume_from_snapshot()
#10  ./aspect-mpiio: aspect::Simulator<3>::run()
#11  ./aspect-mpiio: void run_simulator<3>(std::__cxx11::basic_string<char, std::char_traits<char>, std
::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha
r> > const&, bool, bool, bool)
#12  ./aspect-mpiio: main```

### PR DESCRIPTION
**Pull request by gassmoeller**
In #3967 I introduced a bug for restarting spherical shell models that was reported in #4021. This should fix #4021 and adds a test for a restart with a spherical shell geometry.

### CODE REVIEW

File: source/simulator/checkpoint_restart.cc [hunk 1]
```diff
@@ -456,6 +457,11 @@ namespace aspect
       {
         AssertThrow(false, ExcMessage("Cannot open snapshot mesh file or read the triangulation stored there."));
       }
+
+    // if using a cached mapping, update the cache with the new triangulation
+    if (MappingQCache<dim> *map = dynamic_cast<MappingQCache<dim>*>(&(*mapping)))
+      map->initialize(triangulation,MappingQGeneric<dim>(4));
```
Comment (tjhei) [inline source/simulator/checkpoint_restart.cc:463]: Is there an easy way to query the 4 from the cache? I would like to avoid having duplicated logic like this.

Comment (gassmoeller) [reply source/simulator/checkpoint_restart.cc:463]: Not at the moment, because we do not actually store anything related to the mapping. It is constructed upon start/ after restart and the 4 is just our currently hard-coded degree. But I see why you are concerned. I see two options: Storing the degree of the mapping in a Simulator member variable that gets serialized into the checkpoint, or making the mapping degree an input parameter. The first guarantees that a restart uses the same degree, the second does not (but at least removes the duplicated copies in the code if we use parameters.mapping_degree in both the constructor and here). One complication is that this variable really only makes sense for spherical shells at the moment, boxes always use first order mappings (either MappingCartesian or MappingQ1Eulerian).

Comment (tjhei) [reply source/simulator/checkpoint_restart.cc:463]: Exactly. The parameter with default 4 might be the best option. Anyways, I will merge and leave it up to you if you want to make that change later.

**Review by tjhei — APPROVED** [review]
Awesome, thank you for the quick fix! 👍
