### PR TITLE
Fix particle removal in parallel

### LINKED ISSUE #4067: particle crash viscoelastic_bending_beam_particles.prm
with latest deal.ii master:
```
--------------------------------------------------------
An error occurred in line <131> of file <../source/particles/property_pool.cc> in function
    void dealii::Particles::PropertyPool<dim, spacedim>::deregister_particle(dealii::Particles::PropertyPool<dim, spacedim>::Handle&) [with int dim = 2; int spacedim = 2; dealii::Particles::PropertyPool<dim, spacedim>::Handle = unsigned int]
The violated condition was: 
    currently_available_handles.size() < locations.size()
Additional information: 
    Trying to deallocate a particle when none are allocated. This can
    happen if all handles were deallocated already before calling this
    function.

Stacktrace:
-----------
#0  /home/heister/deal-git/build-64/lib/libdeal_II.g.so.10.0.0-pre: dealii::Particles::PropertyPool<2, 2>::deregister_particle(unsigned int&)
#1  /home/heister/deal-git/build-64/lib/libdeal_II.g.so.10.0.0-pre: dealii::Particles::ParticleHandler<2, 2>::clear_particles()
#2  /home/heister/deal-git/build-64/lib/libdeal_II.g.so.10.0.0-pre: dealii::Particles::ParticleHandler<2, 2>::~ParticleHandler()
#3  /home/heister/deal-git/build-64/lib/libdeal_II.g.so.10.0.0-pre: dealii::Particles::ParticleHandler<2, 2>::~ParticleHandler()
#4  /home/heister/aspect-git/build64/aspect: std::default_delete<dealii::Particles::ParticleHandler<2, 2> >::operator()(dealii::Particles::ParticleHandler<2, 2>*) const
#5  /home/heister/aspect-git/build64/aspect: std::unique_ptr<dealii::Particles::ParticleHandler<2, 2>, std::default_delete<dealii::Particles::ParticleHandler<2, 2> > >::~unique_ptr()
#6  /home/heister/aspect-git/build64/aspect: aspect::Particle::World<2>::~World()
#7  /home/heister/aspect-git/build64/aspect: aspect::Particle::World<2>::~World()
#8  /home/heister/aspect-git/build64/aspect: std::default_delete<aspect::Particle::World<2> >::operator()(aspect::Particle::World<2>*) const
#9  /home/heister/aspect-git/build64/aspect: std::unique_ptr<aspect::Particle::World<2>, std::default_delete<aspect::Particle::World<2> > >::reset(aspect::Particle::World<2>*)
#10  /home/heister/aspect-git/build64/aspect: aspect::Simulator<2>::~Simulator()
#11  /home/heister/aspect-git/build64/aspect: void run_simulator<2>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
#12  /home/heister/aspect-git/build64/aspect: main
--------------------------------------------------------

environment: line 1: 28524 Aborted                 (core dumped) /home/heister/aspect-git/build64/aspect $prm.tmp > /dev/null
run of viscoelastic_bending_beam_particles.prm failed
```

### PR DESCRIPTION
**Pull request by gassmoeller**
Unfortunately #4063 only fixed serial computations. `remove_particles` is a collective function that updates the cache of the particle handler so it is expected to be called on all processes which we dont, and we dont want to store all the local particle iterators we want to remove either. So instead I rewrote the removal logic for 10.0. It also looks much cleaner now. The code could be further improved if the particle_handler had a function `particle_in_cell(cell,particle_index)` that returned the n-th particle in a cell, but that is something to do for the future.

I have verified that this PR, together with the open fixes for deal.II (dealii/dealii#12485) fixes #4067 and the viscoelastic_bending_beam_particles and the viscoelastic_stress_buildup_particles benchmark finish in parallel.

### CODE REVIEW

File: source/particle/world.cc [hunk 1]
```diff
@@ -391,11 +391,19 @@ namespace aspect
                 else if ((particle_load_balancing & ParticleLoadBalancing::remove_particles) &&
                          (n_particles_in_cell > max_particles_per_cell))
                   {
+                    const unsigned int n_particles_to_remove = n_particles_in_cell - max_particles_per_cell;
+
+#if DEAL_II_VERSION_GTE(10,0,0)
+                    for (unsigned int i=0; i < n_particles_to_remove; ++i)
+                      {
+                        auto particle_to_remove = particle_handler->particles_in_cell(cell).begin();
+                        std::advance(particle_to_remove, random_number_generator() % particle_handler->n_particles_in_cell(cell));
```
Comment (bangerth) [inline source/particle/world.cc:400]: This relies on the assumption that the `random_number_generator()` call returns an integer equally distributed between zero and a multiple of `particle_handler->n_particles_in_cell(cell)`, but that's not necessarily true. It could just return zero or one in each call, or 0...127, which is not what you want if you had, for example, 200 particles.

The generic way to do what you want is to use `std::uniform_int_distribution` and let it give you a random integer in the range you want (inclusive):
```suggestion
                        std::advance(particle_to_remove, 
                                     std::uniform_int_distribution<unsigned int>(0, particle_handler->n_particles_in_cell(cell)-1)(random_number_generator());
```

**Review by bangerth — COMMENTED** [review]
Yes, this is nicer. But please fix the one issue with the random number generation.

**Comment by gassmoeller** [comment]
Fixed.

**Review by tjhei — APPROVED** [review]
